// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/portforward/service (interfaces: Logger)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=service . Logger
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", s)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), s)
}

// Error mocks base method.
func (m *MockLogger) Error(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", s)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), s)
}

// Info mocks base method.
func (m *MockLogger) Info(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", s)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), s)
}

// Warn mocks base method.
func (m *MockLogger) Warn(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", s)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), s)
}
